### PR TITLE
fix RenderJobTemplate specIndex error

### PR DESCRIPTION
**Pull request by ShuangMen**
Fix kubecf deploy failure mentioned in https://github.com/cloudfoundry-incubator/quarks-operator/issues/1206

The issue was found whey I tried to deploy kubecf 2.5.8 with multi_az enabled, only one zone pods get running, the others fail with error "no job instance found for spec index '10000'".

I find that the calculation of  `specIndex` was changed since commit
https://github.com/cloudfoundry-incubator/quarks-operator/commit/c6ba7e7391a516f04f676a70e80bf5f488061f49#diff-8d311956cef69b8982593414c29b44676d3e74d69a0e3321d346d8caf56f088c

And when multi_az enabled, below comparison 
https://github.com/cloudfoundry-incubator/quarks-operator/blob/b31c0c41415cee1c2438025fc18f0b3ef126947a/pkg/bosh/manifest/cmd_render_job_tmpls.go#L97
will never find the matching instance and then report a deployment failure.

## Motivation and Context

https://github.com/cloudfoundry-incubator/quarks-operator/issues/1206

## Checklist:

Check item if necessary.

- [ ] Review PRs of changed Quarks dependencies
- [ ] Update this PR after the release of Quarks dependencies

### CODE REVIEW

**Comment by ShuangMen** [comment]
This code has been tested in v6.1.17.
```
$ k get pod -n kubecf
NAME                                     READY   STATUS             RESTARTS   AGE
api-z0-0                                 17/17   Running            1          80m
api-z0-1                                 17/17   Running            1          64m
api-z1-0                                 17/17   Running            1          5m30s
api-z1-1                                 17/17   Running            1          3m38s
auctioneer-0                             6/6     Running            1          81m
bosh-dns-5bb6c47fb7-8wckf                1/1     Running            0          83m
bosh-dns-5bb6c47fb7-wrxk4                1/1     Running            0          83m
cc-worker-z0-0                           6/6     Running            0          80m
cc-worker-z0-1                           6/6     Running            0          63m
cc-worker-z1-0                           6/6     Running            0          80m
cc-worker-z1-1                           6/6     Running            0          63m
cf-apps-dns-68f75c9f4b-8g4qc             1/1     Running            0          84m
database-0                               2/2     Running            0          82m
database-seeder-1b202493bba6fedd-7w7d7   0/2     Completed          0          83m
diego-api-z0-0                           9/9     Running            13         81m
diego-api-z1-0                           9/9     Running            8          81m
diego-cell-z0-0                          12/12   Running            2          80m
diego-cell-z1-0                          12/12   Running            2          80m
doppler-z0-0                             6/6     Running            0          81m
doppler-z1-0                             6/6     Running            0          81m
log-api-z0-0                             9/9     Running            0          80m
log-api-z0-1                             9/9     Running            0          79m
log-api-z1-0                             9/9     Running            0          80m
log-api-z1-1                             9/9     Running            0          70m
log-cache-0                              10/10   Running            0          81m
nats-z0-0                                7/7     Running            0          80m
nats-z0-1                                7/7     Running            0          80m
nats-z1-0                                7/7     Running            0          80m
nats-z1-1                                7/7     Running            0          70m
router-z0-0                              7/7     Running            1          81m
router-z1-0                              7/7     Running            0          81m
scheduler-z0-0                           13/13   Running            1          80m
scheduler-z1-0                           12/13   CrashLoopBackOff   18         80m
singleton-blobstore-z0-0                 8/8     Running            0          81m
uaa-z0-0                                 8/8     Running            6          80m
uaa-z1-0                                 8/8     Running            0          80m
```
And I've do below test:
cf push an app: ok
access the app: ok
check the app logs: ok
```
$ cf apps
Getting apps in org system / space dev as admin...

name    requested state   processes   routes
test1   started           web:1/1     test1.cluster.mytest.cloud

$ cf logs test1
Retrieving logs for app test1 in org system / space dev as admin...

   2020-10-28T02:41:51.52-0400 [APP/PROC/WEB/0] OUT parms=,
   2020-10-28T02:41:51.52-0400 [APP/PROC/WEB/0] OUT parms[0]=
   2020-10-28T02:41:51.52-0400 [APP/PROC/WEB/0] OUT sleeping for 0
   2020-10-28T02:41:51.52-0400 [RTR/1] OUT test1.cluster.mytest.cloud - [2020-10-28T06:41:51.519847711Z] "GET / HTTP/1.1" 200 0 786 "-" "curl/7.64.1" "xxx.17.88.11:53029" "xxx.17.99.179:61002" x_forwarded_for:"xxx.17.103.64, xxx.17.88.11" x_forwarded_proto:"http" vcap_request_id:"6089fb17-b5d6-4f9d-719d-9ebcd3ad7231" response_time:0.007931 gorouter_time:0.000324 app_id:"37e4c24f-6329-402e-8cda-9ef3aec0f3cf" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"6406bb3ac565f9bb" x_b3_spanid:"6406bb3ac565f9bb" x_b3_parentspanid:"-" b3:"6406bb3ac565f9bb-6406bb3ac565f9bb"
   2020-10-28T02:41:51.52-0400 [RTR/1] OUT
```

**Comment by ShuangMen** [comment]
@manno @viovanov, could you review this PR ?

**Review by viovanov — APPROVED** [review]

**Comment by manno** [comment]
Tests are not triggered, because support for PRs from forks is new: https://www.pivotaltracker.com/story/show/175030373

I'm trying  a few things to debug our workflow setup..

**Review by manno — APPROVED** [review]

**Comment by manno** [comment]
@ShuangMen one unit test is failing.

**Comment by ShuangMen** [comment]
The last test case failed at https://github.com/cloudfoundry-incubator/quarks-operator/blob/b31c0c41415cee1c2438025fc18f0b3ef126947a/pkg/bosh/manifest/cmd_render_job_tmpls_test.go#L176

root cause:
'testing/assets/ig-resolved.redis.yml' is setting to multi-az, and specify only one instance for each az.  In such case, the 'specIndex' values will be '0' and '10000'.

But in the test case, it wants to RenderJobTemplates with 'specIndex==1'. That's why the test case failed.

I update the assets file 'testing/assets/ig-resolved.redis.yml'  to have  two instances for each az. Then the 'specIndex' values will be '0' ,'1', '10000' and '10001'. This time it should find the correct job instance.

**Comment by ShuangMen** [comment]
@manno seems the test not triggered.

**Comment by ShuangMen** [comment]
the unit test passed
```
$ bin/test-unit
Test logs are here: /tmp/cf-operator-tests.log
[1604371635] BOSH BPM Suite - 5 specs - 2 nodes ••••• SUCCESS! 98.581284ms
[1604371635] BPM Converter Suite - 60 specs - 2 nodes •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 806.3917ms
[1604371635] BOSH Converter Suite - 8 specs - 2 nodes •••••••• SUCCESS! 210.310227ms
[1604371635] BOSH Manifest Suite - 158 specs - 2 nodes •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 16.644258398s
[1604371635] Quarks Jobs Suite - 9 specs - 2 nodes ••••••••• SUCCESS! 234.556378ms
[1604371635] Controllers Suite - 5 specs - 2 nodes ••••• SUCCESS! 184.655673ms
[1604371635] Boshdeployment Suite - 37 specs - 2 nodes ••••••••••••••••••••••••••••••••••••• SUCCESS! 2.081033493s
[1604371635] QuarksLink Suite - 10 specs - 2 nodes •••••••••• SUCCESS! 273.383555ms
[1604371635] VersionedSecret Suite - 3 specs - 2 nodes ••• SUCCESS! 25.708335ms
[1604371635] WaitService Suite - 5 specs - 2 nodes ••••• SUCCESS! 239.864183ms
[1604371635] BOSH DNS Suite - 11 specs - 2 nodes ••••••••••• SUCCESS! 152.264788ms
[1604371635] Mutate Suite - 13 specs - 2 nodes ••••••••••••• SUCCESS! 183.506066ms
[1604371635] Names Suite - 6 specs - 2 nodes •••••• SUCCESS! 76.858536ms
[1604371635] Operator Image Suite - 1 specs - 2 nodes • SUCCESS! 46.600188ms
[1604371635] Reference Suite - 0 specs - 2 nodes  SUCCESS! 43.874244ms
[1604371635] WithOps Suite - 48 specs - 2 nodes •••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 413.602762ms

Ginkgo ran 16 suites in 1m2.360777159s
Test Suite Passed
```

**Review by manno — APPROVED** [review]

**Comment by manno** [comment]
Wow, I have to approve again to make the workflow run on the current code.

**Comment by ShuangMen** [comment]
@manno , I see there is one case failed, 
```
Run actions-ecosystem/action-add-labels@v1
  with:
    labels: pr-test-queue
    repo: cloudfoundry-incubator/quarks-operator
Error: Error: Input required and not supplied: github_token
Error: Input required and not supplied: github_token
```
but  it looks like the test pipeline issue.

**Comment by ShuangMen** [comment]
@manno, this time the test all passed, can this pr be merged ? Thanks

**Pull request merged**
